CREATE TABLE sale_detail
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sale_id          BIGINT,
    product_id       BIGINT,
    product_quantity INT,
    price            DOUBLE PRECISION,
    CONSTRAINT pk_saledetail PRIMARY KEY (id)
);

ALTER TABLE sale_detail
    ADD CONSTRAINT FK_SALEDETAIL_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE sale_detail
    ADD CONSTRAINT FK_SALEDETAIL_ON_SALE FOREIGN KEY (sale_id) REFERENCES sale (id);