CREATE TABLE product
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    category VARCHAR(255),
    price    DOUBLE PRECISION                        NOT NULL,
    quantity INT                                     NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);