CREATE TABLE sale
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date      date,
    status    VARCHAR(255),
    branch_id BIGINT,
    total     DOUBLE PRECISION,
    CONSTRAINT pk_sale PRIMARY KEY (id)
);

ALTER TABLE sale
    ADD CONSTRAINT FK_SALE_ON_BRANCH FOREIGN KEY (branch_id) REFERENCES branch (id);

CREATE TABLE sale
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date      date,
    status    VARCHAR(255),
    branch_id BIGINT,
    total     DOUBLE PRECISION,
    CONSTRAINT pk_sale PRIMARY KEY (id)
);

ALTER TABLE sale
    ADD CONSTRAINT FK_SALE_ON_BRANCH FOREIGN KEY (branch_id) REFERENCES branch (id);